### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by Turbo87** [krisselden/fast-source-map#12]
I've ported the project to TypeScript in one of my branches and that actually caught a few issues already. Should I open a PR for that or are you not interested in using TypeScript in this project? 

/cc @krisselden @stefanpenner

**Comment by krisselden** [comment]
I'm happy to see it in typescript

**Comment by Turbo87** [comment]
I've based the branch on top of #9, so it would be awesome if you could review and merge that before. Thanks :)
