### ISSUE TITLE
Native extension

### ISSUE THREAD

**Issue by Turbo87** [krisselden/fast-source-map#8]
Since this seems to be such a hot code path: would it make sense to write some of this stuff as a native extension (e.g. using Rust) in addition to the fallback code in JS? If this is mainly used by Ember CLI in node-land and less in the browser this might actually work and have benefits, but I admit that I'm not yet aware of all the potential disadvantages of such an approach.

/cc @stefanpenner @wycats

**Comment by stefanpenner** [comment]
@Turbo87 I wouldn't mind an opt-in native extension, but the developer ergonomics around native extensions today are so poor, we should continue to (by default) ship a fast pure JS one.

neon is a cool idea from the rust world, especially if it could be combined with emscripten to auto-gen a pure JS variant, but allow op-in for those requiring it.

**Comment by Turbo87** [comment]
looks like @mitsuhiko was faster than me: https://github.com/mitsuhiko/rust-sourcemap 😛

**Comment by stefanpenner** [comment]
> looks like @mitsuhiko was faster than me: https://github.com/mitsuhiko/rust-sourcemap 😛

sweet

**Comment by Turbo87** [comment]
seems to be addressed by https://github.com/krisselden/fast-source-map/pull/22
